name: Deploy CDK

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "${{ inputs.environment }}"
