
on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
      environment:
        required: false
        default: ""
        type: string
    secrets:
      envPAT:
        required: true

jobs:

  do-build:
    permissions: write-all
    uses: ./.github/workflows/buildImage.yaml
    with:
      repo: ${{ inputs.repo }}
    secrets:
      envPAT: ${{ secrets.envPAT }}

  post-build-checks:
    needs: do-build
    permissions: write-all
    uses: ./.github/workflows/buildChecks.yaml
    
  deploy-uat:
    needs: post-build-checks
    if: inputs.environment != ''
    permissions: write-all
    uses: ./.github/workflows/deployCdk.yaml
    with:
      environment: ${{ inputs.environment }}
