
on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  yamumma:
    runs-on: ubuntu-latest
    steps:    
      - name: Build and push Docker image
        run: echo ${{ github.sha }}
      - name: Build and push Docker image
        run: echo ${{ github.ref }}

  build:
    runs-on: ubuntu-latest
    steps:
      - id: composite
        uses: DamianBis/actions-demo-lib/.github/workflows/buildImageComposite.yaml@main
        with: 
          repo: ${{ inputs.repo }}
          envPAT: ${{ secrets.envPAT }}


  do-build:
    permissions: write-all
    uses: DamianBis/actions-demo-lib/.github/workflows/buildImage.yaml@main
    with:
      repo: ${{ inputs.repo }}
    secrets:
      envPAT: ${{ secrets.envPAT }}

  post-build-checks:
    needs: do-build
    permissions: write-all
    uses: DamianBis/actions-demo-lib/.github/workflows/buildChecks.yaml@main